language: php

php:
  # using major version aliases
  # aliased to a recent 7.0.x version
  - 7.0
  # aliased to a recent 7.1.x version
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
